### ISSUE TITLE
[1.x.x] java.lang.ClassNotFoundException: "rx.AsyncEmitter$BackpressureMode"

### ISSUE THREAD

**Issue by vganin** [cantrowitz/RxBroadcast#13]
RxBroadcast 1.x depends on 1.2.0 version of RxJava which includes `@Experimental` class `rx.AsyncEmitter`. Later in 1.2.1 it was deprecated in favour of `rx.Emitter`. Finally 1.2.2 `AsyncEmitter` was removed.

So the issue will repro on most modern configurations of libraries that still support RxJava 1.x + RxBroadcast 1.x. Gradle will bump RxJava version to the most recent one by default. In the end the app will crash with `java.lang.ClassNotFoundException` because it will try to load `AsyncEmitter` and will fail.

I suggest that the support for 1.x should be extended (as per RxJava doc it will live until 2018) and `rx.AsyncEmitter` should become `rx.Emitter`.

**Comment by cantrowitz** [comment]
Sounds reasonable. I'll take a look at your PR.

**Comment by vganin** [comment]
Could you create `1.x` branch forked from 1.1.0 tag please? Unfortunately I can't see any way to make PR to  a new branch on Github. It is reasonable base for ongoing `1.x` development, isn't it?

**Comment by cantrowitz** [comment]
created 1.x

**Comment by cantrowitz** [comment]
Just released, it will take a bit to populate.

**Comment by MrVilkaman** [comment]
RxJava version 1.2.7
com.cantrowitz:rxbroadcast:1.1.1
I still have this error!
```
 Caused by: java.lang.ClassNotFoundException: Didn't find class "rx.AsyncEmitter$BackpressureMode" on path: DexPathList[[zip file "/data/app/su.byblos.audiobooks-1/base.apk"],nativeLibraryDirectories=[/data/app/su.byblos.audiobooks-1/lib/arm64, /vendor/lib64, /system/lib64]]
                                         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
                                         at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
                                         at com.cantrowitz.rxbroadcast.RxBroadcast.createBroadcastObservable(RxBroadcast.java:145) 
                                         at com.cantrowitz.rxbroadcast.RxBroadcast.fromBroadcast(RxBroadcast.java:61) 
                                         at com.cantrowitz.rxbroadcast.RxBroadcast.fromBroadcast(RxBroadcast.java:41) 
```

**Comment by cantrowitz** [comment]
try doing a clean rebuild or clear our your cache, something is wrong with your local setup since that class was completely removed in 1.1.1 @MrVilkaman

**Comment by zTrap** [comment]
@cantrowitz don't forget to change version signature in README.md :)
